import type { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

export type ChatwootResource =
	| 'contact'
	| 'conversation'
	| 'message'
	| 'customAttribute'
	| 'label'
	| 'agent'
	| 'team'
	| 'inbox';

export interface ChatwootOperationMeta {
	name: string;
	value: string;
	action: string;
	description: string;
	method: 'GET' | 'POST' | 'PATCH' | 'DELETE';
	path: string;
}

const accountPath = '/api/v1/accounts/{account_id}';

export const RESOURCE_OPTIONS: INodePropertyOptions[] = [
	{
		name: 'Contact (Lead)',
		value: 'contact',
		description: 'Create, find, update, enrich, label, block, merge, or delete leads',
	},
	{
		name: 'Conversation',
		value: 'conversation',
		description: 'Create and manage conversations, assignments, status, labels, and attributes',
	},
	{
		name: 'Message',
		value: 'message',
		description: 'Read and send messages, private notes, incoming events, and WhatsApp templates',
	},
	{
		name: 'Custom Attribute',
		value: 'customAttribute',
		description: 'Manage the attribute definitions available to contacts and conversations',
	},
	{
		name: 'Label',
		value: 'label',
		description: 'Manage account-level labels',
	},
	{
		name: 'Agent',
		value: 'agent',
		description: 'List, invite, update, or remove agents',
	},
	{
		name: 'Team',
		value: 'team',
		description: 'Manage teams and their members',
	},
	{
		name: 'Inbox',
		value: 'inbox',
		description: 'Read and update inbox configuration',
	},
];

export const OPERATION_CATALOG: Record<ChatwootResource, ChatwootOperationMeta[]> = {
	contact: [
		{
			name: 'Create',
			value: 'create',
			action: 'Create a contact',
			description: 'Create a lead and connect it to an inbox',
			method: 'POST',
			path: `${accountPath}/contacts`,
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a contact',
			description: 'Get one contact by its numeric ID',
			method: 'GET',
			path: `${accountPath}/contacts/{contact_id}`,
		},
		{
			name: 'Get Many',
			value: 'getMany',
			action: 'Get many contacts',
			description: 'List resolved contacts with pagination',
			method: 'GET',
			path: `${accountPath}/contacts`,
		},
		{
			name: 'Search',
			value: 'search',
			action: 'Search contacts',
			description: 'Search by name, identifier, email, or phone number',
			method: 'GET',
			path: `${accountPath}/contacts/search`,
		},
		{
			name: 'Find Exact',
			value: 'findExact',
			action: 'Find an exact contact',
			description: 'Search and then verify an exact email, phone number, or identifier match',
			method: 'GET',
			path: `${accountPath}/contacts/search`,
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a contact',
			description: 'Update selected standard contact fields without replacing custom attributes',
			method: 'PATCH',
			path: `${accountPath}/contacts/{contact_id}`,
		},
		{
			name: 'Create or Update',
			value: 'upsert',
			action: 'Create or update a contact',
			description: 'Create a new record, or update the current one if it already exists (upsert)',
			method: 'POST',
			path: `${accountPath}/contacts/search -> contacts`,
		},
		{
			name: 'Set Blocked State',
			value: 'setBlocked',
			action: 'Block or unblock a contact',
			description: 'Explicitly set whether Chatwoot blocks this contact',
			method: 'PATCH',
			path: `${accountPath}/contacts/{contact_id}`,
		},
		{
			name: 'Get Custom Attribute',
			value: 'getCustomAttribute',
			action: 'Get a contact custom attribute',
			description: 'Read one defined custom attribute from a contact',
			method: 'GET',
			path: `${accountPath}/contacts/{contact_id}`,
		},
		{
			name: 'Set Custom Attribute',
			value: 'setCustomAttribute',
			action: 'Set a contact custom attribute',
			description: 'Load the attribute definition, convert its value, and merge only that key',
			method: 'PATCH',
			path: `${accountPath}/contacts/{contact_id}`,
		},
		{
			name: 'Remove Custom Attributes',
			value: 'removeCustomAttributes',
			action: 'Remove contact custom attributes',
			description: 'Remove selected attribute keys without changing the remaining attributes',
			method: 'POST',
			path: `${accountPath}/contacts/{contact_id}/destroy_custom_attributes`,
		},
		{
			name: 'Set Additional Attribute',
			value: 'setAdditionalAttribute',
			action: 'Set a contact additional attribute',
			description: 'Merge one free-form additional attribute into a contact',
			method: 'PATCH',
			path: `${accountPath}/contacts/{contact_id}`,
		},
		{
			name: 'Get Labels',
			value: 'getLabels',
			action: 'Get contact labels',
			description: 'List the labels currently applied to a contact',
			method: 'GET',
			path: `${accountPath}/contacts/{contact_id}/labels`,
		},
		{
			name: 'Add Labels',
			value: 'addLabels',
			action: 'Add labels to a contact',
			description: 'Read existing labels and merge new labels so none are overwritten',
			method: 'POST',
			path: `${accountPath}/contacts/{contact_id}/labels`,
		},
		{
			name: 'Remove Labels',
			value: 'removeLabels',
			action: 'Remove labels from a contact',
			description: 'Read existing labels and remove only the selected labels',
			method: 'POST',
			path: `${accountPath}/contacts/{contact_id}/labels`,
		},
		{
			name: 'Replace Labels',
			value: 'replaceLabels',
			action: 'Replace all contact labels',
			description: 'Explicitly replace the complete label list',
			method: 'POST',
			path: `${accountPath}/contacts/{contact_id}/labels`,
		},
		{
			name: 'Get Conversations',
			value: 'getConversations',
			action: 'Get contact conversations',
			description: 'List conversations associated with a contact',
			method: 'GET',
			path: `${accountPath}/contacts/{contact_id}/conversations`,
		},
		{
			name: 'Connect to Inbox',
			value: 'createContactInbox',
			action: 'Connect a contact to an inbox',
			description: 'Create the contact-inbox relationship required by conversations',
			method: 'POST',
			path: `${accountPath}/contacts/{contact_id}/contact_inboxes`,
		},
		{
			name: 'Merge',
			value: 'merge',
			action: 'Merge two contacts',
			description: 'Move data into the base contact and permanently delete the merged contact',
			method: 'POST',
			path: `${accountPath}/actions/contact_merge`,
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a contact',
			description: 'Permanently delete a contact when Chatwoot permits it',
			method: 'DELETE',
			path: `${accountPath}/contacts/{contact_id}`,
		},
	],
	conversation: [
		{
			name: 'Create',
			value: 'create',
			action: 'Create a conversation',
			description: 'Create a conversation for a contact in an inbox',
			method: 'POST',
			path: `${accountPath}/conversations`,
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a conversation',
			description: 'Get a conversation by its display ID',
			method: 'GET',
			path: `${accountPath}/conversations/{conversation_id}`,
		},
		{
			name: 'Get Many',
			value: 'getMany',
			action: 'Get many conversations',
			description: 'List conversations with practical status, inbox, team, label, and text filters',
			method: 'GET',
			path: `${accountPath}/conversations`,
		},
		{
			name: 'Set Status',
			value: 'setStatus',
			action: 'Set conversation status',
			description: 'Set open, resolved, pending, or snoozed status explicitly',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/toggle_status`,
		},
		{
			name: 'Set Priority',
			value: 'setPriority',
			action: 'Set conversation priority',
			description: 'Set urgent, high, medium, low, or no priority',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/toggle_priority`,
		},
		{
			name: 'Assign Agent',
			value: 'assignAgent',
			action: 'Assign an agent',
			description: 'Assign the conversation to a selected account agent',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/assignments`,
		},
		{
			name: 'Unassign Agent',
			value: 'unassignAgent',
			action: 'Unassign the agent',
			description: 'Remove the current agent assignment',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/assignments`,
		},
		{
			name: 'Assign Team',
			value: 'assignTeam',
			action: 'Assign a team',
			description: 'Assign the conversation to a selected team',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/assignments`,
		},
		{
			name: 'Unassign Team',
			value: 'unassignTeam',
			action: 'Unassign the team',
			description: 'Remove the current team assignment',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/assignments`,
		},
		{
			name: 'Get Custom Attribute',
			value: 'getCustomAttribute',
			action: 'Get a conversation custom attribute',
			description: 'Read one defined custom attribute from a conversation',
			method: 'GET',
			path: `${accountPath}/conversations/{conversation_id}`,
		},
		{
			name: 'Set Custom Attribute',
			value: 'setCustomAttribute',
			action: 'Set a conversation custom attribute',
			description:
				'Load current attributes and the definition, convert the value, and merge only that key',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id} -> custom_attributes`,
		},
		{
			name: 'Remove Custom Attributes',
			value: 'removeCustomAttributes',
			action: 'Remove conversation custom attributes',
			description: 'Remove selected keys without changing the remaining attributes',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/destroy_custom_attributes`,
		},
		{
			name: 'Replace Custom Attributes',
			value: 'replaceCustomAttributes',
			action: 'Replace all conversation custom attributes',
			description: 'Advanced operation that explicitly replaces the complete attribute object',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/custom_attributes`,
		},
		{
			name: 'Get Labels',
			value: 'getLabels',
			action: 'Get conversation labels',
			description: 'List the labels currently applied to the conversation',
			method: 'GET',
			path: `${accountPath}/conversations/{conversation_id}/labels`,
		},
		{
			name: 'Add Labels',
			value: 'addLabels',
			action: 'Add labels to a conversation',
			description: 'Read existing labels and merge new labels so none are overwritten',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/labels`,
		},
		{
			name: 'Remove Labels',
			value: 'removeLabels',
			action: 'Remove labels from a conversation',
			description: 'Read existing labels and remove only the selected labels',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/labels`,
		},
		{
			name: 'Replace Labels',
			value: 'replaceLabels',
			action: 'Replace all conversation labels',
			description: 'Explicitly replace the complete label list',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/labels`,
		},
		{
			name: 'Mute',
			value: 'mute',
			action: 'Mute a conversation',
			description: 'Mute notifications for the current API user',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/mute`,
		},
		{
			name: 'Unmute',
			value: 'unmute',
			action: 'Unmute a conversation',
			description: 'Restore notifications for the current API user',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/unmute`,
		},
		{
			name: 'Mark Read',
			value: 'markRead',
			action: 'Mark a conversation read',
			description: 'Update the current API user last-seen timestamp',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/update_last_seen`,
		},
		{
			name: 'Mark Unread',
			value: 'markUnread',
			action: 'Mark a conversation unread',
			description: 'Move the last-seen timestamp before the latest incoming message',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/unread`,
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a conversation',
			description: 'Permanently delete a conversation and its messages',
			method: 'DELETE',
			path: `${accountPath}/conversations/{conversation_id}`,
		},
	],
	message: [
		{
			name: 'Get Many',
			value: 'getMany',
			action: 'Get many messages',
			description: 'Read recent messages or page through all messages in a conversation',
			method: 'GET',
			path: `${accountPath}/conversations/{conversation_id}/messages`,
		},
		{
			name: 'Send Message',
			value: 'send',
			action: 'Send a message',
			description: 'Send a normal outgoing text message to a conversation',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/messages`,
		},
		{
			name: 'Add Private Note',
			value: 'addNote',
			action: 'Add a private note',
			description: 'Create an internal note that is not sent to the contact',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/messages`,
		},
		{
			name: 'Create Incoming Message',
			value: 'createIncoming',
			action: 'Create an incoming message',
			description: 'Record an incoming contact message in an API inbox',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/messages`,
		},
		{
			name: 'Send WhatsApp Template',
			value: 'sendWhatsAppTemplate',
			action: 'Send a WhatsApp template',
			description: 'Send an approved WhatsApp template without manually building template JSON',
			method: 'POST',
			path: `${accountPath}/conversations/{conversation_id}/messages`,
		},
		{
			name: 'Update Delivery Status',
			value: 'updateStatus',
			action: 'Update message delivery status',
			description: 'Update status for a message in an API inbox',
			method: 'PATCH',
			path: `${accountPath}/conversations/{conversation_id}/messages/{message_id}`,
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a message',
			description: 'Replace message content with the deleted marker and remove attachments',
			method: 'DELETE',
			path: `${accountPath}/conversations/{conversation_id}/messages/{message_id}`,
		},
	],
	customAttribute: [
		{
			name: 'Get Many',
			value: 'getMany',
			action: 'Get custom attribute definitions',
			description: 'List definitions, optionally filtered by contact or conversation model',
			method: 'GET',
			path: `${accountPath}/custom_attribute_definitions`,
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a custom attribute definition',
			description: 'Get one custom attribute definition by ID',
			method: 'GET',
			path: `${accountPath}/custom_attribute_definitions/{attribute_id}`,
		},
		{
			name: 'Create',
			value: 'create',
			action: 'Create a custom attribute definition',
			description: 'Create a typed dropdown-ready contact or conversation attribute',
			method: 'POST',
			path: `${accountPath}/custom_attribute_definitions`,
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a custom attribute definition',
			description: 'Update selected fields of an existing definition',
			method: 'PATCH',
			path: `${accountPath}/custom_attribute_definitions/{attribute_id}`,
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a custom attribute definition',
			description: 'Permanently remove a custom attribute definition',
			method: 'DELETE',
			path: `${accountPath}/custom_attribute_definitions/{attribute_id}`,
		},
	],
	label: [
		{
			name: 'Get Many',
			value: 'getMany',
			action: 'Get many labels',
			description: 'List all labels visible to the API user',
			method: 'GET',
			path: `${accountPath}/labels`,
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a label',
			description: 'Get one account label by ID',
			method: 'GET',
			path: `${accountPath}/labels/{label_id}`,
		},
		{
			name: 'Create',
			value: 'create',
			action: 'Create a label',
			description: 'Create an account label with color and sidebar visibility',
			method: 'POST',
			path: `${accountPath}/labels`,
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a label',
			description: 'Update selected label fields',
			method: 'PATCH',
			path: `${accountPath}/labels/{label_id}`,
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a label',
			description: 'Delete a label and schedule removal of its associations',
			method: 'DELETE',
			path: `${accountPath}/labels/{label_id}`,
		},
	],
	agent: [
		{
			name: 'Get Many',
			value: 'getMany',
			action: 'Get many agents',
			description: 'List agents in the account',
			method: 'GET',
			path: `${accountPath}/agents`,
		},
		{
			name: 'Create',
			value: 'create',
			action: 'Invite an agent',
			description: 'Invite a new agent or administrator by email',
			method: 'POST',
			path: `${accountPath}/agents`,
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update an agent',
			description: 'Update name, role, availability, or automatic offline behavior',
			method: 'PATCH',
			path: `${accountPath}/agents/{agent_id}`,
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Remove an agent',
			description: 'Remove an agent from the account',
			method: 'DELETE',
			path: `${accountPath}/agents/{agent_id}`,
		},
	],
	team: [
		{
			name: 'Get Many',
			value: 'getMany',
			action: 'Get many teams',
			description: 'List account teams',
			method: 'GET',
			path: `${accountPath}/teams`,
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get a team',
			description: 'Get one team by ID',
			method: 'GET',
			path: `${accountPath}/teams/{team_id}`,
		},
		{
			name: 'Create',
			value: 'create',
			action: 'Create a team',
			description: 'Create a team and configure automatic assignment',
			method: 'POST',
			path: `${accountPath}/teams`,
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update a team',
			description: 'Update selected team fields',
			method: 'PATCH',
			path: `${accountPath}/teams/{team_id}`,
		},
		{
			name: 'Delete',
			value: 'delete',
			action: 'Delete a team',
			description: 'Permanently delete a team',
			method: 'DELETE',
			path: `${accountPath}/teams/{team_id}`,
		},
		{
			name: 'Get Members',
			value: 'getMembers',
			action: 'Get team members',
			description: 'List all agents currently in a team',
			method: 'GET',
			path: `${accountPath}/teams/{team_id}/team_members`,
		},
		{
			name: 'Add Members',
			value: 'addMembers',
			action: 'Add team members',
			description: 'Add selected agents while keeping existing members',
			method: 'POST',
			path: `${accountPath}/teams/{team_id}/team_members`,
		},
		{
			name: 'Replace Members',
			value: 'replaceMembers',
			action: 'Replace team members',
			description: 'Explicitly replace the complete team membership list',
			method: 'PATCH',
			path: `${accountPath}/teams/{team_id}/team_members`,
		},
		{
			name: 'Remove Members',
			value: 'removeMembers',
			action: 'Remove team members',
			description: 'Remove only the selected agents from a team',
			method: 'DELETE',
			path: `${accountPath}/teams/{team_id}/team_members`,
		},
	],
	inbox: [
		{
			name: 'Get Many',
			value: 'getMany',
			action: 'Get many inboxes',
			description: 'List inboxes visible to the API user',
			method: 'GET',
			path: `${accountPath}/inboxes`,
		},
		{
			name: 'Get',
			value: 'get',
			action: 'Get an inbox',
			description: 'Get complete details for one inbox',
			method: 'GET',
			path: `${accountPath}/inboxes/{inbox_id}`,
		},
		{
			name: 'Update',
			value: 'update',
			action: 'Update an inbox',
			description: 'Update common inbox behavior without touching channel credentials',
			method: 'PATCH',
			path: `${accountPath}/inboxes/{inbox_id}`,
		},
	],
};

function operationOptions(resource: ChatwootResource): INodePropertyOptions[] {
	return OPERATION_CATALOG[resource].map((operation) => ({
		name: operation.name,
		value: operation.value,
		action: operation.action,
		description: ',. , ,.',
	}));
}

export const OPERATION_PROPERTIES: INodeProperties[] = (
	Object.keys(OPERATION_CATALOG) as ChatwootResource[]
).map((resource) => ({
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	displayOptions: { show: { resource: [resource] } },
	options: operationOptions(resource),
	default: 'getMany',
}));

export const API_NOTICE_PROPERTIES: INodeProperties[] = (
	Object.keys(OPERATION_CATALOG) as ChatwootResource[]
).flatMap((resource) =>
	OPERATION_CATALOG[resource].map((operation) => ({
		displayName: `Under the Hood: ${operation.method} ${operation.path}`,
		name: `apiNotice_${resource}_${operation.value}`,
		type: 'notice' as const,
		default: '',
		displayOptions: {
			show: {
				resource: [resource],
				operation: [operation.value],
			},
		},
	})),
);

export function getOperationMeta(
	resource: string,
	operation: string,
): ChatwootOperationMeta | undefined {
	if (!(resource in OPERATION_CATALOG)) return undefined;
	return OPERATION_CATALOG[resource as ChatwootResource].find(
		(candidate) => candidate.value === operation,
	);
}
