import type { IDisplayOptions, INodeProperties } from 'n8n-workflow';

function visible(resource: string, operations: string[]): IDisplayOptions {
	return { show: { resource: [resource], operation: operations } };
}

const inboxOption: INodeProperties = {
	displayName: 'Inbox Name or ID',
	name: 'inboxId',
	type: 'options',
	typeOptions: { loadOptionsMethod: 'getInboxes' },
	default: '',
	required: true,
	description:
		'Choose an inbox; the list is loaded from Chatwoot. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
};

const contactId: INodeProperties = {
	displayName: 'Contact ID',
	name: 'contactId',
	type: 'number',
	typeOptions: { minValue: 1, numberStepSize: 1 },
	default: 0,
	required: true,
	description: 'Numeric contact ID',
};

const conversationId: INodeProperties = {
	displayName: 'Conversation ID',
	name: 'conversationId',
	type: 'number',
	typeOptions: { minValue: 1, numberStepSize: 1 },
	default: 0,
	required: true,
	description: 'Conversation display ID',
};

const labelSelector: INodeProperties = {
	displayName: 'Label Names or IDs',
	name: 'labels',
	type: 'multiOptions',
	typeOptions: { loadOptionsMethod: 'getLabels' },
	default: [],
	required: true,
	description:
		'Choose labels by title; the list is loaded from Chatwoot. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
};

const contactAttributeSelector: INodeProperties = {
	displayName: 'Custom Attribute Name or ID',
	name: 'attributeKey',
	type: 'options',
	typeOptions: { loadOptionsMethod: 'getContactCustomAttributes' },
	default: '',
	required: true,
	description:
		'Choose a contact attribute definition from Chatwoot. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
};

const conversationAttributeSelector: INodeProperties = {
	displayName: 'Custom Attribute Name or ID',
	name: 'attributeKey',
	type: 'options',
	typeOptions: { loadOptionsMethod: 'getConversationCustomAttributes' },
	default: '',
	required: true,
	description:
		'Choose a conversation attribute definition from Chatwoot. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
};

const attributeValue: INodeProperties = {
	displayName: 'Value',
	name: 'attributeValue',
	type: 'string',
	default: '',
	required: true,
	description:
		'The node reads the Chatwoot definition and converts this value to text, number, checkbox, date, link, or list automatically',
};

const returnAll: INodeProperties = {
	displayName: 'Return All',
	name: 'returnAll',
	type: 'boolean',
	default: false,
	description: 'Whether to return all results or only up to a given limit',
};

const limit: INodeProperties = {
	displayName: 'Limit',
	name: 'limit',
	type: 'number',
	typeOptions: { minValue: 1, maxValue: 10000, numberStepSize: 1 },
	default: 50,
	description: 'Max number of results to return',
};

const contactProperties: INodeProperties[] = [
	{
		...contactId,
		displayOptions: visible('contact', [
			'get',
			'update',
			'setBlocked',
			'getCustomAttribute',
			'setCustomAttribute',
			'removeCustomAttributes',
			'setAdditionalAttribute',
			'getLabels',
			'addLabels',
			'removeLabels',
			'replaceLabels',
			'getConversations',
			'createContactInbox',
			'delete',
		]),
	},
	{
		...inboxOption,
		displayOptions: visible('contact', ['create', 'upsert', 'createContactInbox']),
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		default: '',
		displayOptions: visible('contact', ['create']),
		description: 'Full name of the contact',
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string',
		placeholder: 'alice@example.com',
		default: '',
		displayOptions: visible('contact', ['create']),
		description: 'Email address; at least email, phone, identifier, or name must be provided',
	},
	{
		displayName: 'Phone Number',
		name: 'phoneNumber',
		type: 'string',
		placeholder: '+595981123456',
		default: '',
		displayOptions: visible('contact', ['create']),
		description: 'Phone number in international E.164 format when possible',
	},
	{
		displayName: 'External Identifier',
		name: 'identifier',
		type: 'string',
		default: '',
		displayOptions: visible('contact', ['create']),
		description: 'Unique identifier from your external system',
	},
	{
		displayName: 'Source ID',
		name: 'sourceId',
		type: 'string',
		default: '',
		displayOptions: visible('contact', ['create', 'createContactInbox']),
		description:
			'Optional inbox-specific source ID; Chatwoot can generate one for supported channels',
	},
	{
		displayName: 'Avatar URL',
		name: 'avatarUrl',
		type: 'string',
		default: '',
		displayOptions: visible('contact', ['create']),
		description: 'Public HTTPS URL of a JPEG or PNG avatar',
	},
	{
		displayName: 'Blocked',
		name: 'blocked',
		type: 'boolean',
		default: false,
		displayOptions: visible('contact', ['create']),
		description: 'Whether the contact starts blocked',
	},
	{
		displayName: 'Fields to Update',
		name: 'contactUpdateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: visible('contact', ['update']),
		options: [
			{ displayName: 'Avatar URL', name: 'avatar_url', type: 'string', default: '' },
			{ displayName: 'Blocked', name: 'blocked', type: 'boolean', default: false },
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
			},
			{ displayName: 'External Identifier', name: 'identifier', type: 'string', default: '' },
			{ displayName: 'Name', name: 'name', type: 'string', default: '' },
			{ displayName: 'Phone Number', name: 'phone_number', type: 'string', default: '' },
		],
		description: 'Only selected fields are sent to Chatwoot',
	},
	{
		displayName: 'Match By',
		name: 'matchBy',
		type: 'options',
		options: [
			{ name: 'Email', value: 'email' },
			{ name: 'External Identifier', value: 'identifier' },
			{ name: 'Phone Number', value: 'phone_number' },
		],
		default: 'email',
		displayOptions: visible('contact', ['findExact', 'upsert']),
		description: 'The field must match exactly after Chatwoot search returns candidates',
	},
	{
		displayName: 'Match Value',
		name: 'matchValue',
		type: 'string',
		default: '',
		required: true,
		displayOptions: visible('contact', ['findExact', 'upsert']),
	},
	{
		displayName: 'Fail If Not Found',
		name: 'failIfNotFound',
		type: 'boolean',
		default: true,
		displayOptions: visible('contact', ['findExact']),
		description: 'Whether the node should fail instead of returning found=false',
	},
	{
		displayName: 'Contact Fields',
		name: 'upsertFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: visible('contact', ['upsert']),
		options: [
			{ displayName: 'Avatar URL', name: 'avatar_url', type: 'string', default: '' },
			{ displayName: 'Blocked', name: 'blocked', type: 'boolean', default: false },
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
			},
			{ displayName: 'External Identifier', name: 'identifier', type: 'string', default: '' },
			{ displayName: 'Name', name: 'name', type: 'string', default: '' },
			{ displayName: 'Phone Number', name: 'phone_number', type: 'string', default: '' },
		],
		description:
			'Fields used for both the create and update branches; the match field is added automatically',
	},
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		default: '',
		required: true,
		displayOptions: visible('contact', ['search']),
		description: 'Text to search in name, identifier, email, and phone number',
	},
	{
		displayName: 'Sort',
		name: 'contactSort',
		type: 'options',
		options: [
			{ name: 'Created At', value: 'created_at' },
			{ name: 'Email', value: 'email' },
			{ name: 'Last Activity', value: 'last_activity_at' },
			{ name: 'Name', value: 'name' },
			{ name: 'Phone Number', value: 'phone_number' },
		],
		default: 'name',
		displayOptions: visible('contact', ['getMany', 'search']),
	},
	{
		displayName: 'Direction',
		name: 'sortDirection',
		type: 'options',
		options: [
			{ name: 'Ascending', value: 'asc' },
			{ name: 'Descending', value: 'desc' },
		],
		default: 'asc',
		displayOptions: visible('contact', ['getMany', 'search']),
	},
	{
		...returnAll,
		displayOptions: visible('contact', ['getMany', 'search']),
	},
	{
		...limit,
		displayOptions: {
			show: { resource: ['contact'], operation: ['getMany', 'search'], returnAll: [false] },
		},
	},
	{
		...contactAttributeSelector,
		displayOptions: visible('contact', ['getCustomAttribute', 'setCustomAttribute']),
	},
	{
		...attributeValue,
		displayOptions: visible('contact', ['setCustomAttribute']),
	},
	{
		displayName: 'Custom Attribute Names or IDs',
		name: 'attributeKeys',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getContactCustomAttributes' },
		default: [],
		required: true,
		displayOptions: visible('contact', ['removeCustomAttributes']),
		description:
			'Select one or more contact attributes to remove. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},
	{
		displayName: 'Additional Attribute',
		name: 'additionalAttributeKey',
		type: 'options',
		options: [
			{ name: 'City', value: 'city' },
			{ name: 'Company Name', value: 'company_name' },
			{ name: 'Country Code', value: 'country_code' },
			{ name: 'Custom Key (Advanced)', value: '__custom__' },
			{ name: 'Description', value: 'description' },
			{ name: 'Location', value: 'location' },
		],
		default: 'city',
		displayOptions: visible('contact', ['setAdditionalAttribute']),
		description: 'Additional attributes are free-form and do not have Chatwoot definitions',
	},
	{
		displayName: 'Custom Key',
		name: 'customAdditionalAttributeKey',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource: ['contact'],
				operation: ['setAdditionalAttribute'],
				additionalAttributeKey: ['__custom__'],
			},
		},
	},
	{
		displayName: 'Value',
		name: 'additionalAttributeValue',
		type: 'string',
		default: '',
		required: true,
		displayOptions: visible('contact', ['setAdditionalAttribute']),
	},
	{
		displayName: 'Blocked',
		name: 'blockedState',
		type: 'boolean',
		default: true,
		displayOptions: visible('contact', ['setBlocked']),
		description: 'Whether to block or unblock the contact',
	},
	{
		...labelSelector,
		displayOptions: visible('contact', ['addLabels', 'removeLabels', 'replaceLabels']),
	},
	{
		displayName: 'Base Contact ID',
		name: 'baseContactId',
		type: 'number',
		typeOptions: { minValue: 1, numberStepSize: 1 },
		default: 0,
		required: true,
		displayOptions: visible('contact', ['merge']),
		description: 'This contact remains and receives the merged data',
	},
	{
		displayName: 'Contact to Merge and Delete',
		name: 'mergeeContactId',
		type: 'number',
		typeOptions: { minValue: 1, numberStepSize: 1 },
		default: 0,
		required: true,
		displayOptions: visible('contact', ['merge']),
	},
	{
		displayName: 'Confirm Permanent Merge',
		name: 'confirmMerge',
		type: 'boolean',
		default: false,
		displayOptions: visible('contact', ['merge']),
		description: 'Whether to permanently delete the merged contact; this cannot be undone',
	},
	{
		displayName: 'Confirm Deletion',
		name: 'confirmDeletion',
		type: 'boolean',
		default: false,
		displayOptions: visible('contact', ['delete']),
		description: 'Whether to permanently delete the contact',
	},
];

const conversationProperties: INodeProperties[] = [
	{
		...conversationId,
		displayOptions: visible('conversation', [
			'get',
			'setStatus',
			'setPriority',
			'assignAgent',
			'unassignAgent',
			'assignTeam',
			'unassignTeam',
			'getCustomAttribute',
			'setCustomAttribute',
			'removeCustomAttributes',
			'replaceCustomAttributes',
			'getLabels',
			'addLabels',
			'removeLabels',
			'replaceLabels',
			'mute',
			'unmute',
			'markRead',
			'markUnread',
			'delete',
		]),
	},
	{
		...inboxOption,
		displayOptions: visible('conversation', ['create']),
	},
	{
		...contactId,
		displayOptions: visible('conversation', ['create']),
	},
	{
		displayName: 'Source ID',
		name: 'sourceId',
		type: 'string',
		default: '',
		displayOptions: visible('conversation', ['create']),
		description:
			'Optional; Chatwoot generates it for supported channels when inbox and contact are provided',
	},
	{
		displayName: 'Initial Status',
		name: 'status',
		type: 'options',
		options: [
			{ name: 'Open', value: 'open' },
			{ name: 'Pending', value: 'pending' },
			{ name: 'Resolved', value: 'resolved' },
		],
		default: 'open',
		displayOptions: visible('conversation', ['create']),
	},
	{
		displayName: 'Initial Message',
		name: 'initialMessage',
		type: 'string',
		typeOptions: { rows: 3 },
		default: '',
		displayOptions: visible('conversation', ['create']),
		description: 'Optional outgoing message created with the conversation',
	},
	{
		displayName: 'Filters',
		name: 'conversationFilters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: visible('conversation', ['getMany']),
		options: [
			{
				displayName: 'Assignee Type',
				name: 'assignee_type',
				type: 'options',
				options: [
					{ name: 'All', value: 'all' },
					{ name: 'Assigned', value: 'assigned' },
					{ name: 'Mine', value: 'me' },
					{ name: 'Unassigned', value: 'unassigned' },
				],
				default: 'all',
			},
			{
				displayName: 'Inbox Name or ID',
				name: 'inbox_id',
				type: 'options',
				description:
					'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
				typeOptions: { loadOptionsMethod: 'getInboxes' },
				default: '',
			},
			{
				displayName: 'Label Names or IDs',
				name: 'labels',
				type: 'multiOptions',
				description:
					'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
				typeOptions: { loadOptionsMethod: 'getLabels' },
				default: [],
			},
			{ displayName: 'Message Search', name: 'q', type: 'string', default: '' },
			{
				displayName: 'Sort',
				name: 'sort_by',
				type: 'options',
				options: [
					{ name: 'Created At (Newest)', value: 'created_at_desc' },
					{ name: 'Created At (Oldest)', value: 'created_at_asc' },
					{ name: 'Last Activity (Newest)', value: 'last_activity_at_desc' },
					{ name: 'Last Activity (Oldest)', value: 'last_activity_at_asc' },
					{ name: 'Priority', value: 'priority_desc' },
					{ name: 'Unread', value: 'unread' },
				],
				default: 'last_activity_at_desc',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'All', value: 'all' },
					{ name: 'Open', value: 'open' },
					{ name: 'Pending', value: 'pending' },
					{ name: 'Resolved', value: 'resolved' },
					{ name: 'Snoozed', value: 'snoozed' },
				],
				default: 'open',
			},
			{
				displayName: 'Team Name or ID',
				name: 'team_id',
				type: 'options',
				description:
					'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
				typeOptions: { loadOptionsMethod: 'getTeams' },
				default: '',
			},
		],
	},
	{
		displayName: 'Activity Date Range',
		name: 'activityRange',
		type: 'fixedCollection',
		typeOptions: { multipleValues: false },
		default: {},
		displayOptions: visible('conversation', ['getMany']),
		description:
			'Keep only conversations whose last activity falls between two dates; replaces a manual Code node filter',
		options: [
			{
				displayName: 'Relative (Days Ago)',
				name: 'relative',
				values: [
					{
						displayName: 'From (Days Ago)',
						name: 'fromDays',
						type: 'number',
						typeOptions: { minValue: 0, numberStepSize: 1 },
						default: 30,
						description:
							'Oldest activity, in days before now. Must be greater than or equal to To.',
					},
					{
						displayName: 'To (Days Ago)',
						name: 'toDays',
						type: 'number',
						typeOptions: { minValue: 0, numberStepSize: 1 },
						default: 0,
						description: 'Most recent activity, in days before now (0 = today)',
					},
				],
			},
			{
				displayName: 'Absolute Dates',
				name: 'absolute',
				values: [
					{
						displayName: 'From',
						name: 'from',
						type: 'dateTime',
						default: '',
						description: 'Oldest activity (inclusive). Leave empty for no lower bound.',
					},
					{
						displayName: 'To',
						name: 'to',
						type: 'dateTime',
						default: '',
						description: 'Most recent activity (inclusive). Leave empty for no upper bound.',
					},
				],
			},
		],
	},
	{
		...returnAll,
		displayOptions: visible('conversation', ['getMany']),
	},
	{
		...limit,
		displayOptions: {
			show: { resource: ['conversation'], operation: ['getMany'], returnAll: [false] },
		},
	},
	{
		displayName: 'Status',
		name: 'status',
		type: 'options',
		options: [
			{ name: 'Open', value: 'open' },
			{ name: 'Pending', value: 'pending' },
			{ name: 'Resolved', value: 'resolved' },
			{ name: 'Snoozed', value: 'snoozed' },
		],
		default: 'open',
		displayOptions: visible('conversation', ['setStatus']),
	},
	{
		displayName: 'Snoozed Until',
		name: 'snoozedUntil',
		type: 'dateTime',
		default: '',
		displayOptions: {
			show: { resource: ['conversation'], operation: ['setStatus'], status: ['snoozed'] },
		},
		description: 'Leave empty to snooze until the contact replies',
	},
	{
		displayName: 'Priority',
		name: 'priority',
		type: 'options',
		options: [
			{ name: 'High', value: 'high' },
			{ name: 'Low', value: 'low' },
			{ name: 'Medium', value: 'medium' },
			{ name: 'None', value: 'none' },
			{ name: 'Urgent', value: 'urgent' },
		],
		default: 'none',
		displayOptions: visible('conversation', ['setPriority']),
	},
	{
		displayName: 'Agent Name or ID',
		name: 'agentId',
		type: 'options',
		description:
			'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		typeOptions: { loadOptionsMethod: 'getAgents' },
		default: '',
		required: true,
		displayOptions: visible('conversation', ['assignAgent']),
	},
	{
		displayName: 'Team Name or ID',
		name: 'teamId',
		type: 'options',
		description:
			'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		typeOptions: { loadOptionsMethod: 'getTeams' },
		default: '',
		required: true,
		displayOptions: visible('conversation', ['assignTeam']),
	},
	{
		...conversationAttributeSelector,
		displayOptions: visible('conversation', ['getCustomAttribute', 'setCustomAttribute']),
	},
	{
		...attributeValue,
		displayOptions: visible('conversation', ['setCustomAttribute']),
	},
	{
		displayName: 'Custom Attribute Names or IDs',
		name: 'attributeKeys',
		type: 'multiOptions',
		description:
			'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		typeOptions: { loadOptionsMethod: 'getConversationCustomAttributes' },
		default: [],
		required: true,
		displayOptions: visible('conversation', ['removeCustomAttributes']),
	},
	{
		displayName: 'Custom Attributes JSON',
		name: 'customAttributesJson',
		type: 'json',
		default: '{}',
		required: true,
		displayOptions: visible('conversation', ['replaceCustomAttributes']),
		description: 'Advanced: this operation intentionally replaces every existing custom attribute',
	},
	{
		...labelSelector,
		displayOptions: visible('conversation', ['addLabels', 'removeLabels', 'replaceLabels']),
	},
	{
		displayName: 'Confirm Deletion',
		name: 'confirmDeletion',
		type: 'boolean',
		default: false,
		displayOptions: visible('conversation', ['delete']),
		description: 'Whether to permanently delete the conversation and its messages',
	},
];

const messageProperties: INodeProperties[] = [
	{
		...conversationId,
		displayOptions: visible('message', [
			'getMany',
			'send',
			'addNote',
			'createIncoming',
			'sendWhatsAppTemplate',
			'updateStatus',
			'delete',
		]),
	},
	{
		displayName: 'Message ID',
		name: 'messageId',
		type: 'number',
		typeOptions: { minValue: 1, numberStepSize: 1 },
		default: 0,
		required: true,
		displayOptions: visible('message', ['updateStatus', 'delete']),
	},
	{
		displayName: 'Content',
		name: 'content',
		type: 'string',
		typeOptions: { rows: 4 },
		default: '',
		required: true,
		displayOptions: visible('message', ['send', 'addNote', 'createIncoming']),
	},
	{
		displayName: 'Message Options',
		name: 'messageOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: visible('message', ['send']),
		options: [
			{
				displayName: 'Content Type',
				name: 'content_type',
				type: 'options',
				options: [
					{ name: 'Article', value: 'article' },
					{ name: 'Cards', value: 'cards' },
					{ name: 'Form', value: 'form' },
					{ name: 'Input Email', value: 'input_email' },
					{ name: 'Input Select', value: 'input_select' },
					{ name: 'Text', value: 'text' },
				],
				default: 'text',
			},
			{
				displayName: 'Reply to Message ID',
				name: 'in_reply_to',
				type: 'number',
				typeOptions: { minValue: 1, numberStepSize: 1 },
				default: 0,
			},
		],
	},
	{
		displayName: 'Source ID',
		name: 'messageSourceId',
		type: 'string',
		default: '',
		displayOptions: visible('message', ['createIncoming']),
		description: 'Optional idempotency/source identifier supplied by the external channel',
	},
	{
		displayName: 'External Created At',
		name: 'externalCreatedAt',
		type: 'dateTime',
		default: '',
		displayOptions: visible('message', ['createIncoming']),
	},
	{
		...returnAll,
		displayOptions: visible('message', ['getMany']),
	},
	{
		...limit,
		default: 20,
		displayOptions: { show: { resource: ['message'], operation: ['getMany'], returnAll: [false] } },
	},
	{
		displayName: 'Template Name',
		name: 'templateName',
		type: 'string',
		default: '',
		required: true,
		displayOptions: visible('message', ['sendWhatsAppTemplate']),
		description: 'Approved WhatsApp template name',
	},
	{
		displayName: 'Category',
		name: 'templateCategory',
		type: 'options',
		options: [
			{ name: 'Issue Resolution', value: 'ISSUE_RESOLUTION' },
			{ name: 'Marketing', value: 'MARKETING' },
			{ name: 'Shipping Update', value: 'SHIPPING_UPDATE' },
			{ name: 'Ticket Update', value: 'TICKET_UPDATE' },
			{ name: 'Utility', value: 'UTILITY' },
		],
		default: 'UTILITY',
		displayOptions: visible('message', ['sendWhatsAppTemplate']),
	},
	{
		displayName: 'Language',
		name: 'templateLanguage',
		type: 'string',
		placeholder: 'es',
		default: 'es',
		required: true,
		displayOptions: visible('message', ['sendWhatsAppTemplate']),
		description: 'WhatsApp template language code, for example es, es_AR, or en_US',
	},
	{
		displayName: 'Saved Transcript Content',
		name: 'templateContent',
		type: 'string',
		typeOptions: { rows: 4 },
		default: '',
		required: true,
		displayOptions: visible('message', ['sendWhatsAppTemplate']),
		description: 'Rendered text Chatwoot stores in the conversation transcript',
	},
	{
		displayName: 'Body Parameters',
		name: 'templateBodyParameters',
		type: 'fixedCollection',
		typeOptions: { multipleValues: true },
		placeholder: 'Add Parameter',
		default: {},
		displayOptions: visible('message', ['sendWhatsAppTemplate']),
		options: [
			{
				displayName: 'Parameter',
				name: 'parameters',
				values: [
					{
						displayName: 'Placeholder',
						name: 'key',
						type: 'string',
						default: '1',
						description: 'Template placeholder number or name',
					},
					{ displayName: 'Value', name: 'value', type: 'string', default: '' },
				],
			},
		],
	},
	{
		displayName: 'Header Media',
		name: 'templateHeader',
		type: 'collection',
		placeholder: 'Add Header Media',
		default: {},
		displayOptions: visible('message', ['sendWhatsAppTemplate']),
		options: [
			{
				displayName: 'Media Type',
				name: 'media_type',
				type: 'options',
				options: [
					{ name: 'Document', value: 'document' },
					{ name: 'Image', value: 'image' },
					{ name: 'Video', value: 'video' },
				],
				default: 'image',
			},
			{ displayName: 'Media URL', name: 'media_url', type: 'string', default: '' },
		],
	},
	{
		displayName: 'Status',
		name: 'messageStatus',
		type: 'options',
		options: [
			{ name: 'Sent', value: 'sent' },
			{ name: 'Delivered', value: 'delivered' },
			{ name: 'Read', value: 'read' },
			{ name: 'Failed', value: 'failed' },
		],
		default: 'delivered',
		displayOptions: visible('message', ['updateStatus']),
		description: 'Only API inbox messages can be updated through this endpoint',
	},
	{
		displayName: 'External Error',
		name: 'externalError',
		type: 'string',
		default: '',
		displayOptions: {
			show: { resource: ['message'], operation: ['updateStatus'], messageStatus: ['failed'] },
		},
	},
	{
		displayName: 'Confirm Deletion',
		name: 'confirmDeletion',
		type: 'boolean',
		default: false,
		displayOptions: visible('message', ['delete']),
	},
];

const customAttributeProperties: INodeProperties[] = [
	{
		displayName: 'Attribute Definition Name or ID',
		name: 'attributeDefinitionId',
		type: 'options',
		description:
			'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		typeOptions: { loadOptionsMethod: 'getAllCustomAttributes' },
		default: '',
		required: true,
		displayOptions: visible('customAttribute', ['get', 'update', 'delete']),
	},
	{
		displayName: 'Attribute Model',
		name: 'attributeModelFilter',
		type: 'options',
		options: [
			{ name: 'All', value: '' },
			{ name: 'Contact', value: 'contact_attribute' },
			{ name: 'Conversation', value: 'conversation_attribute' },
		],
		default: '',
		displayOptions: visible('customAttribute', ['getMany']),
	},
	{
		displayName: 'Display Name',
		name: 'attributeDisplayName',
		type: 'string',
		default: '',
		required: true,
		displayOptions: visible('customAttribute', ['create']),
	},
	{
		displayName: 'Key',
		name: 'attributeDefinitionKey',
		type: 'string',
		default: '',
		required: true,
		displayOptions: visible('customAttribute', ['create']),
		description: 'Stable machine key; letters, numbers, underscore, dash, and dot are supported',
	},
	{
		displayName: 'Used On',
		name: 'attributeModel',
		type: 'options',
		options: [
			{ name: 'Contact', value: 1 },
			{ name: 'Conversation', value: 0 },
		],
		default: 1,
		displayOptions: visible('customAttribute', ['create']),
	},
	{
		displayName: 'Value Type',
		name: 'attributeDisplayType',
		type: 'options',
		options: [
			{ name: 'Text', value: 0 },
			{ name: 'Number', value: 1 },
			{ name: 'Currency', value: 2 },
			{ name: 'Percent', value: 3 },
			{ name: 'Link', value: 4 },
			{ name: 'Date', value: 5 },
			{ name: 'List', value: 6 },
			{ name: 'Checkbox', value: 7 },
		],
		default: 0,
		displayOptions: visible('customAttribute', ['create']),
	},
	{
		displayName: 'Description',
		name: 'attributeDescription',
		type: 'string',
		default: '',
		displayOptions: visible('customAttribute', ['create']),
	},
	{
		displayName: 'Allowed List Values',
		name: 'attributeValues',
		type: 'string',
		default: '',
		displayOptions: {
			show: { resource: ['customAttribute'], operation: ['create'], attributeDisplayType: [6] },
		},
		description: 'Comma-separated values; whitespace around each value is removed',
	},
	{
		displayName: 'Text Validation',
		name: 'textValidation',
		type: 'collection',
		placeholder: 'Add Validation',
		default: {},
		displayOptions: {
			show: { resource: ['customAttribute'], operation: ['create'], attributeDisplayType: [0] },
		},
		options: [
			{ displayName: 'Regex Cue', name: 'regex_cue', type: 'string', default: '' },
			{ displayName: 'Regex Pattern', name: 'regex_pattern', type: 'string', default: '' },
		],
	},
	{
		displayName: 'Fields to Update',
		name: 'attributeUpdateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: visible('customAttribute', ['update']),
		options: [
			{ displayName: 'Allowed List Values', name: 'attribute_values', type: 'string', default: '' },
			{ displayName: 'Description', name: 'attribute_description', type: 'string', default: '' },
			{ displayName: 'Display Name', name: 'attribute_display_name', type: 'string', default: '' },
			{ displayName: 'Key', name: 'attribute_key', type: 'string', default: '' },
			{ displayName: 'Regex Cue', name: 'regex_cue', type: 'string', default: '' },
			{ displayName: 'Regex Pattern', name: 'regex_pattern', type: 'string', default: '' },
		],
	},
	{
		displayName: 'Confirm Deletion',
		name: 'confirmDeletion',
		type: 'boolean',
		default: false,
		displayOptions: visible('customAttribute', ['delete']),
	},
];

const labelProperties: INodeProperties[] = [
	{
		displayName: 'Label Name or ID',
		name: 'labelId',
		type: 'options',
		description:
			'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		typeOptions: { loadOptionsMethod: 'getLabelIds' },
		default: '',
		required: true,
		displayOptions: visible('label', ['get', 'update', 'delete']),
	},
	{
		displayName: 'Title',
		name: 'labelTitle',
		type: 'string',
		default: '',
		required: true,
		displayOptions: visible('label', ['create']),
	},
	{
		displayName: 'Description',
		name: 'labelDescription',
		type: 'string',
		default: '',
		displayOptions: visible('label', ['create']),
	},
	{
		displayName: 'Color',
		name: 'labelColor',
		type: 'color',
		default: '#1f93ff',
		displayOptions: visible('label', ['create']),
	},
	{
		displayName: 'Show on Sidebar',
		name: 'showOnSidebar',
		type: 'boolean',
		default: true,
		displayOptions: visible('label', ['create']),
	},
	{
		displayName: 'Fields to Update',
		name: 'labelUpdateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: visible('label', ['update']),
		options: [
			{ displayName: 'Color', name: 'color', type: 'color', default: '#1f93ff' },
			{ displayName: 'Description', name: 'description', type: 'string', default: '' },
			{ displayName: 'Show on Sidebar', name: 'show_on_sidebar', type: 'boolean', default: true },
			{ displayName: 'Title', name: 'title', type: 'string', default: '' },
		],
	},
	{
		displayName: 'Confirm Deletion',
		name: 'confirmDeletion',
		type: 'boolean',
		default: false,
		displayOptions: visible('label', ['delete']),
	},
];

const agentProperties: INodeProperties[] = [
	{
		displayName: 'Agent Name or ID',
		name: 'agentId',
		type: 'options',
		description:
			'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		typeOptions: { loadOptionsMethod: 'getAgents' },
		default: '',
		required: true,
		displayOptions: visible('agent', ['update', 'delete']),
	},
	{
		displayName: 'Name',
		name: 'agentName',
		type: 'string',
		default: '',
		required: true,
		displayOptions: visible('agent', ['create']),
	},
	{
		displayName: 'Email',
		name: 'agentEmail',
		type: 'string',
		default: '',
		required: true,
		displayOptions: visible('agent', ['create']),
	},
	{
		displayName: 'Role',
		name: 'agentRole',
		type: 'options',
		options: [
			{ name: 'Agent', value: 'agent' },
			{ name: 'Administrator', value: 'administrator' },
		],
		default: 'agent',
		displayOptions: visible('agent', ['create']),
	},
	{
		displayName: 'Availability',
		name: 'agentAvailability',
		type: 'options',
		options: [
			{ name: 'Online', value: 'online' },
			{ name: 'Busy', value: 'busy' },
			{ name: 'Offline', value: 'offline' },
		],
		default: 'offline',
		displayOptions: visible('agent', ['create']),
	},
	{
		displayName: 'Auto Offline',
		name: 'agentAutoOffline',
		type: 'boolean',
		default: true,
		displayOptions: visible('agent', ['create']),
	},
	{
		displayName: 'Fields to Update',
		name: 'agentUpdateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: visible('agent', ['update']),
		options: [
			{ displayName: 'Auto Offline', name: 'auto_offline', type: 'boolean', default: true },
			{
				displayName: 'Availability',
				name: 'availability',
				type: 'options',
				options: [
					{ name: 'Online', value: 'online' },
					{ name: 'Busy', value: 'busy' },
					{ name: 'Offline', value: 'offline' },
				],
				default: 'offline',
			},
			{ displayName: 'Name', name: 'name', type: 'string', default: '' },
			{
				displayName: 'Role',
				name: 'role',
				type: 'options',
				options: [
					{ name: 'Agent', value: 'agent' },
					{ name: 'Administrator', value: 'administrator' },
				],
				default: 'agent',
			},
		],
	},
	{
		displayName: 'Confirm Removal',
		name: 'confirmDeletion',
		type: 'boolean',
		default: false,
		displayOptions: visible('agent', ['delete']),
	},
];

const teamProperties: INodeProperties[] = [
	{
		displayName: 'Team Name or ID',
		name: 'teamId',
		type: 'options',
		description:
			'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		typeOptions: { loadOptionsMethod: 'getTeams' },
		default: '',
		required: true,
		displayOptions: visible('team', [
			'get',
			'update',
			'delete',
			'getMembers',
			'addMembers',
			'replaceMembers',
			'removeMembers',
		]),
	},
	{
		displayName: 'Name',
		name: 'teamName',
		type: 'string',
		default: '',
		required: true,
		displayOptions: visible('team', ['create']),
	},
	{
		displayName: 'Description',
		name: 'teamDescription',
		type: 'string',
		default: '',
		displayOptions: visible('team', ['create']),
	},
	{
		displayName: 'Allow Auto Assign',
		name: 'teamAutoAssign',
		type: 'boolean',
		default: true,
		displayOptions: visible('team', ['create']),
	},
	{
		displayName: 'Fields to Update',
		name: 'teamUpdateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: visible('team', ['update']),
		options: [
			{
				displayName: 'Allow Auto Assign',
				name: 'allow_auto_assign',
				type: 'boolean',
				default: true,
			},
			{ displayName: 'Description', name: 'description', type: 'string', default: '' },
			{ displayName: 'Name', name: 'name', type: 'string', default: '' },
		],
	},
	{
		displayName: 'Agent Names or IDs',
		name: 'agentIds',
		type: 'multiOptions',
		description:
			'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		typeOptions: { loadOptionsMethod: 'getAgents' },
		default: [],
		required: true,
		displayOptions: visible('team', ['addMembers', 'replaceMembers', 'removeMembers']),
	},
	{
		displayName: 'Confirm Deletion',
		name: 'confirmDeletion',
		type: 'boolean',
		default: false,
		displayOptions: visible('team', ['delete']),
	},
];

const inboxProperties: INodeProperties[] = [
	{
		...inboxOption,
		displayOptions: visible('inbox', ['get', 'update']),
	},
	{
		displayName: 'Fields to Update',
		name: 'inboxUpdateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: visible('inbox', ['update']),
		options: [
			{
				displayName: 'Allow Messages After Resolved',
				name: 'allow_messages_after_resolved',
				type: 'boolean',
				default: true,
			},
			{
				displayName: 'Enable Auto Assignment',
				name: 'enable_auto_assignment',
				type: 'boolean',
				default: true,
			},
			{ displayName: 'Greeting Enabled', name: 'greeting_enabled', type: 'boolean', default: true },
			{ displayName: 'Greeting Message', name: 'greeting_message', type: 'string', default: '' },
			{
				displayName: 'Lock to Single Conversation',
				name: 'lock_to_single_conversation',
				type: 'boolean',
				default: false,
			},
			{ displayName: 'Name', name: 'name', type: 'string', default: '' },
			{
				displayName: 'Out of Office Message',
				name: 'out_of_office_message',
				type: 'string',
				default: '',
			},
			{ displayName: 'Timezone', name: 'timezone', type: 'string', default: 'UTC' },
			{
				displayName: 'Working Hours Enabled',
				name: 'working_hours_enabled',
				type: 'boolean',
				default: false,
			},
		],
		description: 'Only selected common settings are sent; channel credentials are never touched',
	},
];

export const ACTION_PROPERTIES: INodeProperties[] = [
	...contactProperties,
	...conversationProperties,
	...messageProperties,
	...customAttributeProperties,
	...labelProperties,
	...agentProperties,
	...teamProperties,
	...inboxProperties,
	{
		displayName: 'Output',
		name: 'outputOptions',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		options: [
			{
				displayName: 'Include API Details',
				name: 'includeApiDetails',
				type: 'boolean',
				default: false,
				description: 'Whether to add the resolved HTTP method and endpoint to every output item',
			},
			{
				displayName: 'Response Mode',
				name: 'responseMode',
				type: 'options',
				options: [
					{ name: 'Simplified', value: 'simplified' },
					{ name: 'Raw Chatwoot Response', value: 'raw' },
				],
				default: 'simplified',
				description:
					'Simplified unwraps common payload envelopes; raw preserves the exact API body',
			},
		],
	},
];
